import { type Filters, FilterTypes } from '@libs/filterInputs';

export const filters = {
  sort: {
    type: FilterTypes.Picker,
    label: 'Sắp xếp',
    value: 'view',
    options: [
      { label: 'Không sắp xếp', value: '' },
      { label: 'Mới nhập kho', value: 'new' },
      { label: 'Mới cập nhật', value: 'update' },
      { label: 'Lượt đọc tổng', value: 'view' },
      { label: 'Lượt đọc tuần', value: 'viewweek' },
      { label: 'Lượt đọc ngày', value: 'viewday' },
      { label: 'Lượt thích', value: 'like' },
      { label: 'Lượt theo dõi', value: 'following' },
      { label: 'Lượt đánh dấu', value: 'bookmarked' },
      { label: 'Đề cử', value: 'auto' },
    ],
  },
  minc: {
    type: FilterTypes.Picker,
    label: 'Số chương tối thiểu',
    value: '0',
    options: [
      { label: 'Tất cả', value: '0' },
      { label: '> 50', value: '50' },
      { label: '> 100', value: '100' },
      { label: '> 200', value: '200' },
      { label: '> 500', value: '500' },
      { label: '> 1000', value: '1000' },
      { label: '> 1500', value: '1500' },
      { label: '> 2000', value: '2000' },
    ],
  },
  category: {
    type: FilterTypes.Picker,
    label: 'Thể loại chính',
    value: '',
    options: [
      { label: 'Tất cả', value: '' },
      { label: 'Huyền huyễn', value: 'hh' },
      { label: 'Đô thị', value: 'dt' },
      { label: 'Ngôn tình', value: 'nt' },
      { label: 'Võng du', value: 'vd' },
      { label: 'Khoa học viễn tưởng', value: 'kh' },
      { label: 'Lịch sử', value: 'ls' },
      { label: 'Đồng nhân', value: 'dn' },
      { label: 'Dị năng', value: 'dna' },
      { label: 'Linh dị', value: 'ld' },
      { label: 'Light Novel', value: 'ln' },
    ],
  },
  type: {
    type: FilterTypes.Picker,
    label: 'Loại truyện',
    value: '',
    options: [
      { label: 'Tất cả', value: '' },
      { label: 'Truyện sáng tác', value: 'sangtac' },
      { label: 'Truyện dịch', value: 'dich' },
      { label: 'Truyện tranh', value: 'comic' },
      { label: 'Txt dịch tự động', value: 'txt' },
      { label: 'Truyện scan ảnh', value: 'scan' },
    ],
  },
  step: {
    type: FilterTypes.Picker,
    label: 'Trạng thái đăng',
    value: '',
    options: [
      { label: 'Tất cả', value: '' },
      { label: 'Hoàn thành', value: '3' },
      { label: 'Còn tiếp', value: '1' },
      { label: 'Tạm ngưng', value: '2' },
      { label: 'Không tạm ngưng', value: '5' },
    ],
  },
  host: {
    type: FilterTypes.Picker,
    label: 'Nguồn truyện',
    value: '',
    options: [
      { label: 'Tất cả', value: '' },
      { label: '[Vip] fanqie (Cà Chua)', value: 'fanqie' },
      { label: '[Vip] qidian (Khởi Điểm)', value: 'qidian' },
      { label: '[Vip] ciweimao', value: 'ciweimao' },
      { label: '[Vip] faloo (Phi Lư)', value: 'faloo' },
      { label: '[Vip] jjwxc (Tấn Giang)', value: 'jjwxc' },
      { label: '[Vip] sfacg', value: 'sfacg' },
      { label: '[Vip] zongheng (Tung Hoành)', value: 'zongheng' },
      { label: '[Free] 69shu', value: '69shu' },
      { label: '[Free] tadu', value: 'tadu' },
      { label: '[Free] qimao (7 Mèo)', value: 'qimao' },
      { label: '[Free] idejian', value: 'idejian' },
      { label: '[LN] linovel', value: 'linovel' },
      { label: '[LN] wenku8', value: 'wenku8' },
    ],
  },
  tag: {
    type: FilterTypes.CheckboxGroup,
    label: 'Nhãn',
    value: [],
    options: [
      { label: 'Đô Thị', value: 'dothi' },
      { label: 'Xuyên Qua', value: 'xuyenqua' },
      { label: 'Hệ Thống', value: 'hethong' },
      { label: 'Huyền Huyễn', value: 'huyenhuyen' },
      { label: 'Ngôn Tình', value: 'ngontinh' },
      { label: 'Đồng Nhân', value: 'dongnhan' },
      { label: 'Trùng Sinh', value: 'trungsinh' },
      { label: 'Lịch Sử', value: 'lichsu' },
      { label: 'Khoa Huyễn', value: 'khoahuyen' },
      { label: 'Tiên Hiệp', value: 'tienhiep' },
      { label: 'Võ Hiệp', value: 'vohiep' },
      { label: 'Sảng Văn', value: 'sangvan' },
      { label: 'Light Novel', value: 'lightnovel' },
      { label: 'Linh Dị', value: 'linhdi' },
      { label: 'Kỳ Huyễn', value: 'kyhuyen' },
      { label: 'Tận Thế', value: 'tanthe' },
      { label: 'Ngọt Sủng', value: 'ngotsung' },
      { label: 'Sân Trường', value: 'santruong' },
      { label: 'Nhiệt Huyết', value: 'nhiethuyet' },
      { label: 'Nhanh Xuyên', value: 'nhanhxuyen' },
    ],
  },
} satisfies Filters;
