import esbuild from 'esbuild';
import fs from 'fs';
import path from 'path';
import process from 'process';
import fastGlob from 'fast-glob';
const globSync = fastGlob.globSync;

// Find all entry points (index.js) in plugin folders generated by tsc
const entryPointsFiles = globSync('.tsc-out/*/*/index.js', {
  ignore: ['.tsc-out/multisrc/**'],
});

const entryPoints = entryPointsFiles
  .map(ep => {
    // ep format: .tsc-out/language/pluginName/index.js
    const parts = ep.split('/');
    const lang = parts[1];
    const name = parts[2];
    return {
      in: ep,
      out: `${lang}/${name}`,
      lang,
      name,
    };
  })
  .filter(ep => {
    return !fs.existsSync(path.join('plugins', ep.lang, ep.name, 'BROKEN'));
  });

const createRecursiveProxy = () => {
  const target = {};
  const handler = {
    get(target, prop) {
      if (prop === 'get') return a => a;
      if (!target[prop]) target[prop] = createRecursiveProxy();
      return target[prop];
    },
  };
  return new Proxy(target, handler);
};

async function build() {
  console.log(`Found ${entryPoints.length} plugins to build.`);
  fs.writeFileSync(
    '.tsc-out/package.json',
    JSON.stringify({ type: 'commonjs' }),
  );

  await esbuild.build({
    entryPoints: entryPoints.map(ep => ({ in: ep.in, out: ep.out })),
    bundle: true,
    minify: true,
    outdir: '.js/plugins',
    format: 'cjs',
    target: 'es5',
    plugins: [
      {
        name: 'external-non-relative',
        setup(build) {
          build.onResolve({ filter: /.*/ }, args => {
            // Allow entry points
            if (args.kind === 'entry-point') return;
            // If it's a relative import, let esbuild bundle it
            if (args.path.startsWith('.')) return;
            // Everything else is external (e.g. '@libs/fetch', 'cheerio')
            return { path: args.path, external: true };
          });
        },
      },
    ],
  });

  console.log('Building webview scripts...');
  const proxyRequire = () => createRecursiveProxy();

  for (const ep of entryPoints) {
    const webviewTs = path.join(
      'plugins',
      ep.lang,
      ep.name,
      'webview',
      'index.ts',
    );
    const webviewJs = path.join(
      'plugins',
      ep.lang,
      ep.name,
      'webview',
      'index.js',
    );

    let webviewEntry = null;
    if (fs.existsSync(webviewTs)) webviewEntry = webviewTs;
    else if (fs.existsSync(webviewJs)) webviewEntry = webviewJs;

    if (webviewEntry) {
      try {
        const rawCode = fs.readFileSync(
          path.join('.js', 'plugins', ep.out + '.js'),
          'utf-8',
        );
        const plugin = Function(
          'require',
          'module',
          `const exports = module.exports = {}; 
          ${rawCode}; 
          return exports.default`,
        )(proxyRequire, {});

        if (plugin.customJS) {
          console.log(`[Webview] ${ep.name} -> ${plugin.customJS}`);
          await esbuild.build({
            entryPoints: [webviewEntry],
            bundle: true,
            minify: true,
            outfile: path.join('public', 'static', plugin.customJS),
            format: 'iife',
            target: 'es2020',
          });
        }
      } catch (err) {
        console.error(`Failed to build webview for ${ep.name}:`, err);
      }
    }
  }

  console.log('Plugins built successfully.');
}

build().catch(e => {
  console.error('Build failed', e);
  process.exit(1);
});
